- hosts: localhost
  user: root

  # https://www.cloudera.com/documentation/enterprise/5-13-x/topics/cm_sg_cm_users_principals.html

  tasks:
  - group:
      name: hadoop
      system: yes

  - user:
      name: "{{item}}"
      system: yes
      createhome: no
    with_items:
        - flume
        - hbase
        - hdfs
        - hive
        - httpfs
        - hue
        - apache
        - impala
        - kafka
        - kudu
        - mapred
        - oozie
        - solr
        - spark
        - sentry
        - sqoop
        - yarn
        - zookeeper

    
  - user:
      name: hdfs
      system: yes
      createhome: no
      groups: [hadoop]

  - user:
      name: impala
      system: yes
      createhome: no
      groups: [hive]

  - user:
      name: mapred
      system: yes
      createhome: no
      groups: [hadoop]

  - user:
      name: yarn
      system: yes
      createhome: no
      groups: [hadoop]


