- hosts: localhost

  tasks:
  - file:
      path: /opt/cloudera/parcel-repo
      state: directory
      mode: 0755
      owner: cloudera-scm
      group: cloudera-scm
  
  - get_url:
      url: "https://archive.cloudera.com/cdh5/parcels/{{ lookup('env','CDH_VERSION') }}/CDH-{{ lookup('env','CDH_VERSION') }}-1.cdh{{ lookup('env','CDH_VERSION') }}.p0.3-el7.parcel"
      dest: /opt/cloudera/parcel-repo/

  - get_url:
      url: "http://archive.cloudera.com/cdh5/parcels/{{ lookup('env','CDH_VERSION') }}/manifest.json"
      dest: /opt/cloudera/parcel-repo/

  - get_url:
      url: "https://archive.cloudera.com/cdh5/parcels/{{ lookup('env','CDH_VERSION') }}/CDH-{{ lookup('env','CDH_VERSION') }}-1.cdh{{ lookup('env','CDH_VERSION') }}.p0.3-el7.parcel.sha1"
      dest: "/opt/cloudera/parcel-repo/CDH-{{ lookup('env','CDH_VERSION') }}-1.cdh{{ lookup('env','CDH_VERSION') }}.p0.3-el7.parcel.sha"


