---
- hosts: localhost
  tasks:
  -  yum_repository:
        name: cloudera-manager
        description: Cloudera Manager repository
        baseurl: https://archive.cloudera.com/cm5/redhat/7/x86_64/cm/{{ lookup('env','CDH_VERSION') }}/
        gpgkey: https://archive.cloudera.com/cdh5/redhat/7/x86_64/cdh/RPM-GPG-KEY-cloudera
        gpgcheck: yes
        enabled: yes
  - yum:
        name: oracle-j2sdk1.7

  - shell: echo /usr/java/$(ls -t /usr/java/ | grep -e "jdk.*-cloudera" | head -1)
    register: java_home

  - local_action: debug msg="JAVA_HOME={{java_home.stdout}}"

  - lineinfile:
        path: "{{item}}"
        regexp: '^JAVA_HOME='
        line: "JAVA_HOME={{java_home.stdout}}"
        create: true
        backup: true
    with_items:
          - /etc/default/cloudera-scm-agent
          - /etc/profile.d/java.sh
          - /etc/default/bigtop-utils
