---


- hosts: localhost
  tasks:
  -  yum_repository:
        name: MariaDB
        description: Cloudera Manager repository
        baseurl: http://yum.mariadb.org/10.2.9/centos7-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes
        enabled: yes
  - yum:
        name: "{{item}}"
    with_items:
          - MariaDB-server
          - MariaDB-client
          - galera
          - MariaDB-tokudb-engine

  - file:
      path: /usr/share/java
      state: directory
      mode: 0755
      owner: root
      group: root

  - file:
      path: /tmp/mysql-connector-java
      state: directory
      mode: 0755
      owner: root
      group: root

  - unarchive:
      src: https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-5.1.42.tar.gz
      dest: /tmp/mysql-connector-java
      remote_src: yes

  - copy:
      src: /tmp/mysql-connector-java/mysql-connector-java-5.1.42/mysql-connector-java-5.1.42-bin.jar
      dest: /usr/share/java/mysql-connector-java.jar
      remote_src: true

  - file:
      path: /tmp/mysql-connector-java
      state: absent


  - yum:
        name: "{{item}}"
        state: latest
    with_items:
          - mod_ssl
          - m4
          - libverto-libevent
          - keyutils-libs-devel
          - postgresql-libs
          - cups-libs
          - gperftools-libs
          - cups-client
          - fontconfig
          - avahi-libs
          - redhat-lsb-submod-security
          - net-tools
          - boost-program-options
          - ntp
          - perf
          - MySQL-python
          - libselinux-devel 
          - apr-util
          - openssl-devel
          - openldap
          - openssl
          - fontpackages-filesystem
          - mailcap
          - libsepol-devel
          - perl-PlRPC
          - perl-IO-Compress
          - mc
          - libunwind
          - libcom_err-devel
          - libverto-devel
          - perl-Net-Daemon
          - apr
          - perl-Compress-Raw-Bzip2
          - perl-Compress-Raw-Zlib
          - krb5-workstation
          - perl-DBI
          - gd
          - iproute
          - autogen-libopts
          - psmisc
          - httpd-tools
          - cyrus-sasl-gssapi
          - redhat-lsb-core
          - krb5-devel
          - libevent
          - httpd
          - perl-Data-Dumper
          - spax
          - libXpm
          - patch
          - iotop
          - haproxy
          - krb5-libs
          - krb5-server
          - fuse-libs
          - libkadm5
          - libcgroup-tools
          - python-psycopg2
          - zlib-devel
          - pcre-devel
          - fuse
          - nginx-all-modules
          - nginx-mod-stream
          - ssmtp
          - zvbi-fonts
          - nginx-mod-http-perl
          - nload
          - nginx-mod-http-image-filter
          - nginx-filesystem
          - nginx
          - jemalloc
          - nginx-mod-http-geoip
          - nginx-mod-http-xslt-filter
          - htop 
          - screen
          - openssh-server
          - openssh-clients
          - nano
          - telnet
          - sssd


